# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a4ef0b8ac8634681992a11ccd9d369c44e04eb23aac92c39f1219141fe9e440586d86e07a892db86c1696b9746a707bcfc001f591c05795f003f77701382fc

test:
  secret_key_base: 9b8dbab704e02b7e2997f753abfe4fe816796e5c54a6ae3c21b4f88bf31add63115349a4f0f75031e3aa404d64cdc609d4b66b7946712d003efcd1a2cc3ea796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
